<?php

namespace SAS\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * ActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitiesRepository extends EntityRepository
{
	public function findActivities()
	{
		return $this->createQueryBuilder('a')
					->getQuery()
					->getResult();
	}
}
