<?php

namespace SAS\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{
	public function findSlide()
	{
		return $this->createQueryBuilder('s')
					->getQuery()
					->getResult();
	}
}
